version: "2"
services:
  api:
    image: ${DOCKER_USER}/goweb
    labels:
      traefik.http.routers.goweb-http.rule: Host(`${DOMAIN}`)
      traefik.http.routers.goweb-http.entrypoints: http
      traefik.http.routers.goweb-http.middlewares: redirect@file
      traefik.http.routers.goweb-https.rule: Host(`${DOMAIN}`)
      traefik.http.routers.goweb-https.entrypoints: https
      traefik.http.routers.goweb-https.middlewares: compress@file, web-limit@file
      traefik.http.routers.goweb-https.tls: "true"
      traefik.http.routers.goweb-https.tls.certresolver: default
      traefik.http.services.goweb-service.loadbalancer.server.port: "1080"
    restart: on-failure
    read_only: true
    cpu_shares: 128
    mem_limit: 25165824
    security_opt:
      - no-new-privileges
